{% set name = "fortnet" %}
{% set version = "0.7.3" %}
{% set build = 4 %}
{% set mpi = mpi or "nompi" %}
{% set origin = "vanderhe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ origin }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20e285b098f1417be96c6353aa034658f1e8190683177efab56e3bbabfffd777

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [not linux]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ name|lower }} * {{ mpi_prefix }}_*
    - {{ pin_subpackage( name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - python >=3.7
    - h5py
    - numpy >=1.14.5
    - cmake >=3.16
    - ninja
  host:
    - mpifx * mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - libblas
    - hdf5
    - hdf5 * nompi_*
  run:
    - {{ pin_compatible('mpifx', max_pin='x.x') }} mpi_{{ mpi }}_*  # [mpi != "nompi"]

test:
  commands:
    - export OMPI_MCA_plm=isolated OMPI_MCA_btl_vader_single_copy_mechanism=none OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi"]
    - test -f $PREFIX/bin/fnet
    - fnet | grep "Error in opening file"  # [mpi == "nompi" and build_platform == target_platform]
    - mpiexec $PREFIX/bin/fnet | grep "Error in opening file"  # [mpi != "nompi" and build_platform == target_platform]
    - test -f $PREFIX/lib/libfortnet${SHLIB_EXT}

about:
  home: https://github.com/vanderhe/fortnet
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE
    - COPYING
    - COPYING.LESSER
    - external/fsockets/LICENSE
    - external/xmlf90/LICENSE
  summary: Fortnet, a software package for training Behler-Parrinello neural networks
  doc_url: https://fortnet.readthedocs.io
  dev_url: https://github.com/vanderhe/fortnet

extra:
  recipe-maintainers:
    - vanderhe
